# Generated by Django 3.2.11 on 2022-01-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reply',
            name='bid',
            field=models.IntegerField(),
        ),
    ]
